services:
  postgres:
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - dev_redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      CI: "true"
      LOG_LEVEL: debug
      HOST: 0.0.0.0
      PORT: 8000
      DB_SSL: "false"
      REDIS_DB: 0
    command: sh -c "pnpm dev"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules

  mail-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      DB_SSL: "false"
      REDIS_DB: 0
    command: sh -c "pnpm worker:mail:dev"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  dev_postgres_data:
  dev_redis_data:
